### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by caneko** [DanielBok/copulae#14]
There's a typo in line 4 of
https://copulae.readthedocs.io/en/stable/copulae/archimedean/index.html

Original:
However, more specifically, an Archimedean is defined as
<img src="https://render.githubusercontent.com/render/math?math=C(\textbf{u}) = \psi(\psi^{-1}(u_1), \dots, \psi(d_d)) \quad \textbf{u} \in [0, 1]^d">

Correct version: 

<img src="https://render.githubusercontent.com/render/math?math=C(\textbf{u}) = \psi(\psi^{-1}(u_1), \dots, \psi(u_d)) \quad \textbf{u} \in [0, 1]^d">

the <img src="https://render.githubusercontent.com/render/math?math=d\^{\text{th}}"> uniform random variable <img src="https://render.githubusercontent.com/render/math?math=u_d"> has been mistaken for  <img src="https://render.githubusercontent.com/render/math?math=d_d">

BTW
I'm not familiar with the rst file, so I don't know how to correctly make a commit and PR sry.

**Comment by DanielBok** [comment]
Good catch! Also, it should be phi inverse as well. Will update it ASAP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
