### ISSUE TITLE
Copulae

### ISSUE THREAD

**Issue by Ruiting-ting** [DanielBok/copulae#16]
Dear Daniel

I would like to ask you a question:
When I applied the Copulae Package, I encountered one problem:
![1db07116622ea5be8a26ecf7ba9d19d](https://user-images.githubusercontent.com/67915931/86610647-ede9ee80-bfad-11ea-9ee6-163e56cf23da.png)

But one month ago, I could use this package. So weird.

And I am writing my thesis, and I am looking forward to your reply

Thanks
Ruiting

**Comment by DanielBok** [comment]
Hello Ruiting, 

Do you have the script to reproduce the issue? By default the `bounds` property cannot be overwritten.

```python
  ...: import numpy as np
  ...: import pandas as pd
  ...: 
  ...: from copulae import GaussianCopula
  ...: 
  ...: df = pd.read_csv("gmcm.csv")
  ...: cop = GaussianCopula(2)
  ...: cop.fit(df + np.random.uniform(-1e-6, 1e-6, df.shape))
  ...: 
Out[3]: <copulae.elliptical.gaussian.GaussianCopula at 0x13faf4804f0>

  ...: cop.bounds
Out[4]: (array([-1.000001]), array([1.000001]))

  ...: cop.bounds = "anything"
Traceback (most recent call last):
  File "<ipython-input-5-a15dc11f8a0a>", line 1, in <module>
    cop.bounds = "anything"
AttributeError: can't set attribute
```
