### ISSUE TITLE
Heads up that your version requirement rules out colab by default 

### ISSUE THREAD

**Issue by microprediction** [DanielBok/copulae#17]
Google colab...

Collecting copulae
  Downloading https://files.pythonhosted.org/packages/0b/b3/00723b63c2d985efaba8df6c48aaefdd7fc35bbf09b6ed4936fa0b6400c6/copulae-0.5.0.tar.gz (774kB)
     |████████████████████████████████| 778kB 7.7MB/s 
ERROR: Package 'copulae' requires a different Python: 3.6.9 not in '>=3.7'

**Comment by DanielBok** [comment]
Hello, if using Google colab, would it be possible to use a 3.7+ runtime? 

The reason why it’s 3.7+ is due to optimisation made in the typing module from 3.6 to 3.7

**Comment by microprediction** [comment]
Good idea
https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory
 
 




This electronic message, including its attachments, contains information from Janus Henderson Investors. Janus Henderson Investors is the name under which various entities, including Janus Capital Management LLC, Perkins Investment Management LLC and Intech
 Investment Management LLC provide investment products and services. All of these companies are wholly owned subsidiaries of Janus Henderson Group plc (incorporated in Jersey, registered no.101484, registered office 47 Esplanade, St Helier, Jersey JE1 0BD).
 This email contains information which is confidential and may be privileged and attorney work product, intended solely for the use of the individual or entity named above. Your personal information will be kept in accordance with the applicable data privacy
 laws and Janus Henderson’s Privacy Policy. A copy of the document is available under the Privacy Policy section of our website at www.janushenderson.com and in hard copy by sending a request to privacy@janushenderson.com If you are not the intended recipient,
 be aware that you must not read this email and that any disclosure, copying, distribution or use of the contents of this email is prohibited. If you have received this email in error, please immediately notify the sender and delete the original email and its
 attachments without reading or saving in any manner. .

**Comment by arbitrage-technology** [comment]
also, would like if possible to make copulae avalaible on 3.6 because of Colab...

**Comment by DanielBok** [comment]
Alright, I'll do a backport of it together with the next release

**Comment by DanielBok** [comment]
Published 0.6.0 which supports 3.6. Closing this together with #18.
