### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by muggle14** [DanielBok/copulae#25]
Hello, 

I am trying to use Gaussian copula mixture with non-gaussian distributions or empirical distributions. I am not sure, how can I get the dependence structure for non-gaussian distributions.  

Sorry didn't find another way to ask this?

**Comment by DanielBok** [comment]
Hello,

I believe what you are looking for is the general copula where you can specify the distribution of the marginals and also the dependency structure. 

I would refer you to https://copulae.readthedocs.io/en/latest/copulae/marginal/index.html. 

There's an example right at the top on how it can be with the Gaussian copula. 

Do note that presently, the distribution of the marginal must be from scipy's continuous distribution family. 

Hope it helps
