### ISSUE TITLE
different results when comparing with R ‘copula’

### ISSUE THREAD

**Issue by mhanedCBNU** [DanielBok/copulae#26]
Hi,
I am trying to reproduce some results from an experiment I have done in r using the package ‘copula’.
all the results match except when the data has zeros:
here is an example: I use the sample parameters in both sides [empirical copula with no somthing]

When the data has zeros: (results don't match)
data:
x                              
0.8720320          
0.9472037          
0.3241581          
0.9226000         
0.9763799         
y
0.4154456   
0.0000000
0.0000000
0.0000000
 0.0000000

resulted cdf in r : 0.4, 0.0, 0.0, 0.0, 0.0
resulted cdf using "copulae" package: 0.4, 0.6, 0.2, 0.4, 0.8

Another example with no zeros: (results match)
data:
x                        
0.8993826,   
0.8591301,   
0.2108277,   
0.0000000,   
0.2508839,   
y
0.9433767
0.7802619
0.5243279
0.9659404
0.5459261

resulted cdf in r : 0.8, 0.6, 0.2, 0.2, 0.4
resulted cdf using "copulae" package: 0.8, 0.6, 0.2, 0.2, 0.4

here is my script: 

from copulae import EmpiricalCopula
import pandas as pd 

df = pd.DataFrame(list(zip(l, l1)), columns =['x', 'y']) 
emp_cop = EmpiricalCopula(2, df, smoothing="none")
data = emp_cop.data  
print(emp_cop.cdf(data))

I tried to look into the code to figure out where this difference comes from but with no success? any idea?

**Comment by DanielBok** [comment]
Hello,

I believe the issue is due to the data casting as pseudo-observations. For now, it will be best if you cast your data into pseudo-obervations both as the input marginal and also for deriving the CDF.

In a later version, I will rewrite it such that the constructor can take in the input marginals without first casting (i.e. does not need to be between 0 and 1). However, the CDF input will still need to be specified as the unit marginals (i.e. between 0 and 1)

For now, the following code snippet should aid in your work

```python
import pandas as pd

from copulae import EmpiricalCopula
from copulae.core import pseudo_obs

df1 = pd.DataFrame({
    "x": [0.8720320, 0.9472037, 0.3241581, 0.9226000, 0.9763799],
    "y": [0.4154456, 0, 0, 0, 0],
})

cop1 = EmpiricalCopula(2, df1)
print(cop1.cdf(cop1.pobs(df1)))

df2 = pd.DataFrame({
    "x": [0.8993826, 0.8591301, 0.2108277, 0.0000000, 0.2508839],
    "y": [0.9433767, 0.7802619, 0.5243279, 0.9659404, 0.5459261]
})

cop2 = EmpiricalCopula(2, pseudo_obs(df2))
print(cop2.cdf(pseudo_obs(df2)))
```

As for the corresponding r code, 

```r
library(copula)

df1 <- data.frame(x = c(0.8720320, 0.9472037, 0.3241581, 0.9226000, 0.9763799),
                  y = c(0.4154456, 0, 0, 0, 0))

# the default copula empCopula uses ties.method 'max'  but the pobs uses 'average'
# the copulae package uses 'average' by default
cop1 <- empCopula(df1, ties.method = 'average')
pCopula(pobs(df1, ties.method = 'average'), cop1)
```
