### ISSUE TITLE
Constants used in the marginal cdf function of gaussian mixture copula

### ISSUE THREAD

**Issue by muggle14** [DanielBok/copulae#31]
Hi Daniel, 

I want to understand the logic behind this function. Any reference to paper/book behind the constants and overall approach would be highly appreciated. 

def gmm_marginal_cdf(x: np.ndarray, param: GMCParam):
    """
    Approximates the inverse cdf of the input given the GMC parameters
    Parameters
    ----------
    x : np.ndarray
        Vector of quantiles
    param : GMCParam
        The Gaussian Mixture Copula parameters
    Returns
    -------
    np.ndarray
        Cumulative distribution function evaluated at `x`
    """

    sigmas = np.repeat(np.sqrt([np.diag(c) for c in param.covs]).T[np.newaxis, ...], len(x), axis=0)
    means = np.repeat(param.means.T[np.newaxis, ...], len(x), axis=0)

    **a1 = 0.3480242
    a2 = -0.0958798
    a3 = 0.7478556
    rho = 0.47047
    sqrt2 = 1.4142136**

    _zi = (np.repeat(x[..., np.newaxis], param.n_clusters, axis=2) - means) / (sigmas * sqrt2)
    za = np.abs(zi)
    t = 1 / (1 + rho * za)_
    chunk = 0.5 * (a1 * t + a2 * t ** 2 + a3 * t ** 3) * np.exp(-(za ** 2))
    return np.where(zi < 0, chunk, 1 - chunk) @ param.

**Comment by DanielBok** [comment]
Hello, the approximation is applied marginally. Formula is taken from Abramowitz and Stegun 7.1.25

http://people.math.sfu.ca/~cbm/aands/page_299.htm

**Comment by muggle14** [comment]
Many thanks, superb!
