### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by kaleb-keny** [DanielBok/copulae#35]
Hey @DanielBok , happy new year & MC , just wanted to ask you about the last release, whenever I run a frank cop, it seems to start print things in stdout... maybe they are residuals that are being printed, maybe some verbose is set to 1 in the frankcopula... I tried looking to where that was, but didn't manage 😅  
Thanks again

**Comment by DanielBok** [comment]
Oops. Sounds like I messed up somewhere. I'll take a look at it.

**Comment by kaleb-keny** [comment]
I might have misspoke, I was looking over the package I had, and it didn't seem to be the latest one and I might have fiddled with it earlier adding a print statement, sorry if i wasted your time on that...
