### ISSUE TITLE
 cannot import name 'Ties' from 'copulae.types' (

### ISSUE THREAD

**Issue by Zakariae-drabech** [DanielBok/copulae#36]
In [3]: import copulae                                                          
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-ec9e0e684536> in <module>
----> 1 import copulae

~/anaconda3/lib/python3.7/site-packages/copulae/__init__.py in <module>
      1 from copulae._version import get_versions
----> 2 from copulae.archimedean import *
      3 from copulae.elliptical import *
      4 from copulae.empirical import *
      5 from copulae.indep import *

~/anaconda3/lib/python3.7/site-packages/copulae/archimedean/__init__.py in <module>
----> 1 from .clayton import ClaytonCopula
      2 from .frank import FrankCopula
      3 from .gumbel import GumbelCopula
      4 
      5 __all__ = ['ClaytonCopula', 'FrankCopula', 'GumbelCopula']

~/anaconda3/lib/python3.7/site-packages/copulae/archimedean/clayton.py in <module>
      2 import numpy.random as rng
      3 
----> 4 from copulae.copula import Summary, TailDep
      5 from copulae.core import EPS, valid_rows_in_u
      6 from copulae.stats import random_uniform

~/anaconda3/lib/python3.7/site-packages/copulae/copula/__init__.py in <module>
      1 from .abstract import AbstractCopula
----> 2 from .base import BaseCopula, TailDep
      3 from .summary import Summary

~/anaconda3/lib/python3.7/site-packages/copulae/copula/base.py in <module>
      5 
      6 from copulae.copula.abstract import AbstractCopula
----> 7 from copulae.copula.estimator import CopulaEstimator
      8 from copulae.core import pseudo_obs
      9 from copulae.types import Array, Numeric

~/anaconda3/lib/python3.7/site-packages/copulae/copula/estimator/__init__.py in <module>
----> 1 from .estimator import fit_copula, EstimationMethod

~/anaconda3/lib/python3.7/site-packages/copulae/copula/estimator/estimator.py in <module>
      6 from copulae.core import tri_indices
      7 from copulae.stats import pearson_rho
----> 8 from copulae.types import Array, Ties
      9 from copulae.utility.dict import merge_dict
     10 from .corr_inversion import estimate_corr_inverse_params

ImportError: cannot import name 'Ties' from 'copulae.types' (/home/zakariae/anaconda3/lib/python3.7/site-packages/copulae/types.py)

**Comment by DanielBok** [comment]
Can you state your package version?

I could not reproduce error. Here's what I did

```
conda create -n my_env python=3.7
conda activate my_env
conda install copulae -y
python
>>> import copulae
```

worked fine
