### ISSUE TITLE
EmpiricalCopula does not work

### ISSUE THREAD

**Issue by SKantar** [DanielBok/copulae#40]
Concretely, I executed the code you provided as an example:
 
from copulae import EmpiricalCopula
from copulae.datasets import load_marginal_data
df = load_marginal_data()
df.head(3)
    STUDENT      NORM       EXP
0 -0.485878  2.646041  0.393322
1 -1.088878  2.906977  0.253731
2 -0.462133  3.166951  0.480696
emp_cop = EmpiricalCopula(3, df, smoothing="beta")
data = emp_cop.data  # getting the pseudo-observation data (this is the converted df)
data[:3]
array([[0.32522493, 0.1886038 , 0.55781406],
       [0.15161613, 0.39953349, 0.40953016],
       [0.33622126, 0.65611463, 0.62645785]])
# must feed pseudo-observations into cdf
emp_cop.cdf(data[:2])
array([0.06865595, 0.06320104])
emp_cop.pdf([[0.5, 0.5, 0.5]])

The problem is that whatever arguments I input into emp_cop.pdf([[0.5, 0.5, 0.5]]), I get the same output 0.009268568506099015. For example, if you run emp_cop.pdf([[0.62, 0.91, 0.34]]) I again get 0.00926856850609901. Per my understanding, this number should represent a copula density (pdf) which should vary for different combinations of pseudo-observation values. Yet, it is not the case.
Any advice from your side would be highly appreciated. I created a Collab notebook you can directly access if you have a few minutes to help: https://colab.research.google.com/drive/1GQT7T4HcaDwT2zlCPPa22hGPASBUJTAV?usp=sharing .

**Comment by DanielBok** [comment]
Yes you are right. This is actually something leftover from issue #21. Back then, I forgot to fix the pdf method. It should be resolved when 0.7.2 is deployed.. likely by tomorrow

**Comment by DanielBok** [comment]
Should be fixed now
