### ISSUE TITLE
the summary( ) got converging error

### ISSUE THREAD

**Issue by toriejiang** [DanielBok/copulae#46]

**Comment by toriejiang** [comment]
<img width="516" alt="截屏2021-05-09 下午1 49 10" src="https://user-images.githubusercontent.com/64896755/117561932-7dc85f80-b0cd-11eb-932b-bd24f128b599.png">

**Comment by DanielBok** [comment]
It quite likely just means that the optimiser could not find a global minimum when searching for the model parameters. 

Many reasons why that could happen.
