### ISSUE TITLE
Fixing Correlation Matrix if copulae.fit()

### ISSUE THREAD

**Issue by Loek44** [DanielBok/copulae#50]
Hi Daniel,

I am working on a project and I want to give a fixed correlation matrix to a student t copula. This is easily done after the fit and overwriting the correlation matrix. However, is it possible, in the same manner as fixing the degrees of freedom beforehand, to fix the correlation matrix? This will heavily improve my computation time in copulae.fit(). Thanks in advance.

Warm regards, 
Loek

**Comment by DanielBok** [comment]
I'm guessing you want to fix the correlation matrix but optimize for the best degree of freedom. This is not possible with the current setup.

Also, would that yield a significantly better outcome? You can test it quite quickly by checking the log likelihood of the data when you fix the correlation matrix and alter the df manually. Given that you already have the ideal correlation matrix, I doubt you even need to fit at all.

**Comment by Loek44** [comment]
Great suggestion, thanks for the insight.
