### ISSUE TITLE
Ver 0.7.7 - Kendall Tau not supported for Student Copula

### ISSUE THREAD

**Issue by simrhodes** [DanielBok/copulae#57]
When using `method = "itau"` for Student Copula it returns the following error for line 38 of copulae\copula\estimator\corr_inversion.py in estimate_corr_inverse_params(copula, data, type_):

36     if is_elliptical(copula):
     37         estimate = icor
---> 38         copula.params[:] = estimate
     39     elif is_archimedean(copula):
     40         estimate = np.mean(icor)

TypeError: 'StudentParams' object does not support item assignment

Using GaussianCopula  with  `method = "itau"` does not return an error

**Comment by DanielBok** [comment]
Fixed in next release. For `itau` the degree of freedom can't be changed
