### ISSUE TITLE
Fit Summary

### ISSUE THREAD

**Issue by beatrizcastro1** [DanielBok/copulae#58]
According to you documentation of this [library](https://copulae.readthedocs.io/en/latest/examples/usage_guide.html) when you do `t_cop.sumary()` (in this case for a student copula) it should also return the fit summary of it, however and as we can see in the code it just returns the Degree of Freedom and Correlation Matrix (normal summary) and not the other information it should return according to the documentatio (see attached image). Is there any intention of completing this or was that part in the documentation a mistake. Thanks for the help.

![image](https://github.com/DanielBok/copulae/assets/142844951/4cdf5d8b-a68a-4eca-9dec-9b5847011516)

**Comment by DanielBok** [comment]
Don't think I'll fix it, if you want the fit summary, call `cop.summary('fit')`
