### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by julioasotodv** [DanielBok/copulae#60]
Not an issue.

I just wanted to thank you your work in this library. It is challenging to find good copula implementations in Python, and subjectively I believe your library is the best one I have found so far.

Thanks!

**Comment by DanielBok** [comment]
Oh thank you! I haven't been actively upgrading this because of work but your kind words will give me the motivation to do so when I have the time!

**Comment by jondo** [comment]
I guess this can be closed :-)
