### ISSUE TITLE
An error occurred while importing copulae

### ISSUE THREAD

**Issue by piper0124** [DanielBok/copulae#61]
File "copulae\special\_specfunc.pyx", line 1, in init copulae.special._specfunc
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
copulae version：0.7.8
python：3.9
THANKS

**Comment by DanielBok** [comment]
Which OS are you using? I tested with Windows and python:3.9-slim docker image?

**Comment by piper0124** [comment]
I did some research last night，there are not much information on this in China.
        So I tried updating the numpy to the latest version(1.26.0)，and the problems went away ：）
Nice Copulae.
        
            
        
    
         
        
            
                        
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/9/2023 17:23
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [DanielBok/copulae] An error occurred while importing copulae(Issue #61)
        
      
    
  

Which OS are you using? I tested with Windows and python:3.9-slim docker image?
