### ISSUE TITLE
when I fit the model, it runs so slow

### ISSUE THREAD

**Issue by xueyuan1990** [DanielBok/copulae#7]
g_cop = elliptical.GaussianCopula(dim=ndim)
 print("fit the copula to inputmatrix (shape = %s)" % (inputmatrix.shape,)) #(150,120)
 g_cop.fit(inputmatrix)

**Comment by DanielBok** [comment]
Given a D dimension dataset, the Gaussian copula will have D * (D - 1) / 2 parameters to fit. The data set you're working with has quite a lot of features, thus this will lengthen the time taken to find the optimal parameters.

Another thing you might want to note is that your data set is quite small (very little row data). You might want to consider other alternatives than fitting an elliptical copula.

**Comment by xueyuan1990** [comment]
Thank you for your answer. But I don't know which copula I should choose to get  correlation matrix like Gaussian Copula. The archimedean copula is only parameterized by a single theta.

**Comment by DanielBok** [comment]
I’m not certain about your problem domain and can’t make any definitive suggestions. 

I’d suggest 
1) collecting more data
2) preprocessing to reduce the dimension of the data
3) using other processes / models for your problem
4) re-evaluating your problem and data again
5) see if there are any ways to set some priors in the data with existing business domain knowledge
